import {
  Anchor,
  Button,
  Container,
  Group,
  Image,
  Stack,
  Text,
  Title,
} from '@mantine/core'
import { IconArrowLeft, IconBrandGithub } from '@tabler/icons-react'

const REPO_URL = 'https://github.com/elena-s-thomas/mirth-hapi-fhir'

function DiagramFigure({
  src,
  alt,
  caption,
}: {
  src: string
  alt: string
  caption: string
}) {
  return (
    <Stack gap="xs">
      <div
        style={{
          width: '100%',
          padding: '1.5rem',
          borderRadius: '8px',
          backgroundColor: '#ffffff',
          border: '1px solid #e9ecef',
        }}
      >
        <Image
          src={src}
          alt={alt}
          style={{
            width: '100%',
            height: 'auto',
            maxHeight: '700px',
            objectFit: 'contain',
          }}
        />
      </div>
      <Text size="sm" c="gray.6" ta="center" fs="italic">
        {caption}
      </Text>
    </Stack>
  )
}

export default function Hl7FhirTestbedPage() {
  return (
    <main style={{ backgroundColor: '#f8f9fa', minHeight: '100vh', paddingBottom: '4rem' }}>
      <Container size="md" py="xl">
        <Stack gap="xl">
          <Group justify="space-between">
            <Button
              component="a"
              href="/#projects"
              variant="subtle"
              color="gray.7"
              leftSection={<IconArrowLeft size={16} />}
            >
              Back to Portfolio
            </Button>
            <Button
              component="a"
              href={REPO_URL}
              target="_blank"
              variant="light"
              color="gray"
              rightSection={<IconBrandGithub size={16} />}
            >
              View Source on GitHub
            </Button>
          </Group>

          <Stack gap="md">
            <Text size="sm" c="blue.6" fw={600} tt="uppercase" style={{ letterSpacing: '0.05em' }}>
              Healthcare Integration Project
            </Text>
            <Title order={1} size="2.5rem" fw={700} c="dark.8">
              HL7 v2 to FHIR Integration Testbed
            </Title>
            <Text size="xl" c="gray.7" lh={1.6}>
              A reproducible local pipeline for practicing the troubleshooting workflow that
              integration engineers, application specialists, and PACS administrators rely on
              every day &mdash; reading Mirth&apos;s Message Browser, distinguishing transport
              failures from transformer errors from silent data corruption, and knowing which
              ACK code means what.
            </Text>
            <Text size="lg" c="gray.7" lh={1.6}>
              A Python CLI sends MLLP-framed HL7 v2 messages into Mirth Connect, which transforms
              each one into a FHIR Patient resource and POSTs it to a HAPI FHIR R4 server. Every
              step is visible in Mirth&apos;s Message Browser &mdash; the same tool used to debug
              production interfaces. Nine deliberate error overlays (missing segments, bad date
              formats, unescaped delimiters, dropped MLLP framing) fill the browser with realistic
              failure modes so the troubleshooting practice is grounded, not theoretical.
            </Text>
          </Stack>

          <Stack gap="lg">
            <Title order={2} size="1.75rem" fw={600} c="dark.8">
              The system at a glance
            </Title>
            <Text size="lg" c="gray.7" lh={1.6}>
              The testbed runs two services in Docker: Mirth Connect (the integration engine) and
              HAPI FHIR (the FHIR R4 server). A Python CLI on the host sends HL7 v2 messages into
              Mirth; a separate <code>curl</code> read path queries HAPI directly. The two flows
              touch HAPI through different network paths on purpose &mdash; an architectural
              detail with real consequences for debugging.
            </Text>
            <DiagramFigure
              src="/mirth-hapi-fhir/03-system-architecture.svg"
              alt="System architecture diagram showing the host, Docker, and the Mirth and HAPI containers"
              caption="The full host + Docker topology. The write path leaves Mirth, traverses host.docker.internal, and re-enters HAPI through the host port mapping."
            />
            <Text size="lg" c="gray.7" lh={1.6}>
              One detail worth knowing: the ACK that Mirth returns is generated by{' '}
              <strong>Mirth</strong>, not by HAPI. An <code>AA</code> (Application Accept) means
              Mirth accepted the message &mdash; it does <em>not</em> mean HAPI stored it
              successfully. Production systems usually wire Mirth&apos;s response transformer to
              inspect HAPI&apos;s HTTP status and downgrade the ACK to <code>AE</code> or{' '}
              <code>AR</code> on failure; otherwise senders get false confirmations. This testbed
              keeps the naïve behavior on purpose, because spotting that gap is one of the things
              the project teaches.
            </Text>
          </Stack>

          <Stack gap="lg">
            <Title order={2} size="1.75rem" fw={600} c="dark.8">
              Two standards, one hospital
            </Title>
            <Text size="lg" c="gray.7" lh={1.6}>
              HL7 v2 (from 1989) is pipe-delimited messaging over MLLP/TCP. FHIR (from 2014) is
              REST and JSON over HTTP. Hospitals run both side-by-side &mdash; v2 carries the
              high-volume real-time event traffic (admissions, lab results, imaging orders) while
              FHIR is the modern API surface that web and mobile apps consume. &ldquo;Integration
              troubleshooting&rdquo; in this world almost always means making v2 traffic produce
              correct FHIR resources, which is why this testbed exists.
            </Text>
            <DiagramFigure
              src="/mirth-hapi-fhir/02-v2-vs-fhir.svg"
              alt="Side-by-side comparison of an HL7 v2 message and a FHIR Patient resource"
              caption="Same patient, two representations. Both standards encode the same clinical facts but with completely different wire formats and structural assumptions."
            />
            <Text size="lg" c="gray.7" lh={1.6}>
              A field-by-field mapping looks straightforward on a slide. In practice the work
              hides in the edge cases: a date with no separators, a gender code the spec
              doesn&apos;t list, an unescaped delimiter that shifts every PID component one slot
              to the right. The error overlays in this project reproduce each of those, so the
              symptoms become familiar before they show up in production.
            </Text>
          </Stack>

          <Stack gap="lg">
            <Title order={2} size="1.75rem" fw={600} c="dark.8">
              Inside Mirth Connect
            </Title>
            <Text size="lg" c="gray.7" lh={1.6}>
              Mirth (also called NextGen Connect) is the most widely deployed integration engine
              in U.S. healthcare. Its building block is the channel: a one-way pipeline with a
              source (where data arrives) and one or more destinations (where transformed data
              gets sent). Each channel has filters and transformers that mutate the message as it
              flows through.
            </Text>
            <DiagramFigure
              src="/mirth-hapi-fhir/04-mirth-anatomy.svg"
              alt="Anatomy of a Mirth channel showing source connector, transformer, filter, and destination connector"
              caption="The integration-engine pattern: listener → filter → transformer → destination. Once you know this shape, Rhapsody, InterSystems IRIS, Cloverleaf, and Corepoint all read the same way."
            />
            <Text size="lg" c="gray.7" lh={1.6}>
              In this testbed the channel is small but complete: a TCP listener on port 6661 that
              strips MLLP framing, a JavaScript source transformer that normalizes PID fields
              (date format, gender code) into a <code>channelMap</code>, and an HTTP Sender
              destination that expands those values into a FHIR Patient JSON body and PUTs it to
              HAPI. The whole thing fits on one screen of Mirth&apos;s admin client &mdash; which
              is precisely the point. The admin GUI is where most of the day-to-day work of an
              interface analyst happens, and being comfortable navigating it is the skill the
              project trains.
            </Text>
          </Stack>

          <Stack gap="lg">
            <Title order={2} size="1.75rem" fw={600} c="dark.8">
              Inside HAPI FHIR
            </Title>
            <Text size="lg" c="gray.7" lh={1.6}>
              HAPI FHIR is the reference implementation of a FHIR server &mdash; the open-source
              project that most commercial FHIR servers (including a substantial share of EHR
              vendor offerings) build on or fork from. The server handles resource validation,
              search indexing, and persistence; in this testbed it uses an in-process H2
              database, which is what makes the whole stack run on a laptop without any
              external dependencies.
            </Text>
            <DiagramFigure
              src="/mirth-hapi-fhir/05-hapi-fhir-anatomy.svg"
              alt="Anatomy of the HAPI FHIR server showing REST endpoints, resource providers, and storage"
              caption="HAPI FHIR&rsquo;s internal layout. The REST layer accepts resource operations; the resource providers validate against FHIR profiles; the persistence layer indexes searchable fields into H2."
            />
            <Text size="lg" c="gray.7" lh={1.6}>
              Two FHIR-specific behaviors are worth pointing out, because they shape how the
              testbed feels to use. First, <strong>conditional update</strong>: when Mirth PUTs to{' '}
              <code>/fhir/Patient?identifier=...|MRN</code>, HAPI searches for a Patient with
              that identifier, updates the resource if found, creates it if not, and returns{' '}
              <code>200</code> or <code>201</code> accordingly. That&apos;s why re-sending the
              same canonical patient doesn&apos;t produce duplicates. Second,{' '}
              <strong>search bundles</strong>: a GET that matches multiple resources comes back
              wrapped in a Bundle of type <code>searchset</code>, not as a raw array &mdash; a
              FHIR-ism that surprises engineers used to plain REST.
            </Text>
          </Stack>

          <Stack gap="lg">
            <Title order={2} size="1.75rem" fw={600} c="dark.8">
              Following one message end to end
            </Title>
            <Text size="lg" c="gray.7" lh={1.6}>
              The clearest way to internalize how the pieces fit is to follow one message
              through the whole pipeline. From the CLI building the HL7 v2 bytes, through MLLP
              framing on the wire, through Mirth&apos;s parser and transformer, through the HTTP
              PUT, through HAPI&apos;s conditional update, all the way back to the ACK the CLI
              prints. Every step has a place in the Message Browser; every step has a failure
              mode an error overlay can trigger.
            </Text>
            <DiagramFigure
              src="/mirth-hapi-fhir/06-message-lifecycle.svg"
              alt="Step-by-step lifecycle of one HL7 v2 message moving through the pipeline"
              caption="One ADT^A01 message, ten labelled checkpoints. Each checkpoint corresponds to a tab in Mirth&rsquo;s Message Browser where you can see exactly what the data looked like at that moment."
            />
            <Text size="lg" c="gray.7" lh={1.6}>
              The pedagogically interesting failure modes are the silent ones. A non-standard
              date format makes <code>birthDate</code> extract as an empty string &mdash; Mirth
              still returns <code>AA</code>, HAPI happily stores the Patient, and nobody notices
              until somebody queries the data weeks later. The Message Browser&apos;s{' '}
              <strong>Mappings</strong> tab is the only place that surfaces the problem at the
              moment it happens. Knowing to look there, and knowing what a healthy{' '}
              <code>channelMap</code> looks like compared to a malformed one, is the difference
              between &ldquo;the interface is fine&rdquo; and &ldquo;the interface is fine
              <em> and I checked</em>.&rdquo;
            </Text>
          </Stack>

          <Stack gap="lg">
            <Title order={2} size="1.75rem" fw={600} c="dark.8">
              Reference: the acronyms
            </Title>
            <Text size="lg" c="gray.7" lh={1.6}>
              Every healthcare interoperability conversation accumulates acronyms quickly. This
              one-page glossary collects the terms that come up across the rest of the project.
            </Text>
            <DiagramFigure
              src="/mirth-hapi-fhir/01-acronym-glossary.svg"
              alt="Glossary of healthcare integration acronyms: HL7, v2, FHIR, MLLP, ACK, ADT, PID, MSH, MRN"
              caption="The acronyms that appear in every HL7 integration job description, with one-line definitions."
            />
          </Stack>

          <div
            style={{
              backgroundColor: '#ffffff',
              padding: '2rem',
              borderRadius: '8px',
              border: '1px solid #e9ecef',
            }}
          >
            <Stack gap="md">
              <Group gap="sm" align="center">
                <div
                  style={{
                    width: '40px',
                    height: '40px',
                    borderRadius: '50%',
                    backgroundColor: '#339af0',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'white',
                    fontSize: '20px',
                  }}
                >
                  🔧
                </div>
                <Title order={3} size="1.25rem" fw={600} c="dark.7">
                  Why I built this
                </Title>
              </Group>
              <Text size="md" c="gray.7" lh={1.6}>
                The job of an interface analyst is not writing channels &mdash; vendors and
                consultants do most of that. The job is reading the Message Browser when
                something has gone wrong, forming a hypothesis about which stage of the pipeline
                broke, and either fixing it or filing a precise enough ticket that someone else
                can. That work is hard to practice without access to a real integration engine
                and real failure traffic. This testbed makes both available on a laptop, with
                deliberate failures already wired up, so the practice loop is short and the
                feedback is honest.
              </Text>
              <Group gap="md" mt="sm">
                <Button
                  component="a"
                  href={REPO_URL}
                  target="_blank"
                  variant="filled"
                  color="dark.7"
                  leftSection={<IconBrandGithub size={16} />}
                >
                  View Source on GitHub
                </Button>
                <Button
                  component="a"
                  href="/#projects"
                  variant="subtle"
                  color="gray.7"
                  leftSection={<IconArrowLeft size={16} />}
                >
                  Back to all projects
                </Button>
              </Group>
            </Stack>
          </div>

          <Anchor href="/" c="gray.6" ta="center" size="sm">
            Elena Thomas &middot; Healthcare Informatics Portfolio
          </Anchor>
        </Stack>
      </Container>
    </main>
  )
}
